### ISSUE TITLE
Avoid full page refresh for smoother experience

### ISSUE THREAD

**Issue by srid** [srid/ema#3]
- [ ] Currently when the user clicks on a link, it does a whole page refresh; disconnecting and reopening the websocket connection. This is slow, and we should consider using websockets to do a quick page switch, when using the dev server.
- [x] Might as well use this opportunity to try reconnecting the websocket on ghcid reload ~~prior to doing a full refresh (as fallback)~~. -- Done in #6

Both approaches will require 

- [x] the browser explicitly requesting the HTML for the given route, and then handling the response. i.e, two-way communication (rather than one-way as it is right now).  -- Done in #6

Finally, perhaps 

- [x] display a visual indicator (as hinted to by @TheMatten) during this re-connect stage so the user knows what happens on the browser whilst ghcid reloads (which can sometimes lead to a cold reboot taking a few seconds). -- Done in #6
